# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
project 'CBVoiceTest.xcodeproj'


# 去掉由pod引入的第三方库的警告，需要更新命令才生效
inhibit_all_warnings!

target 'CBVoiceTest' do

    pod 'CBBasicUtils'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end
end

end


